[package]
name = "bdk_chain"
version = "0.23.2"
edition = "2021"
rust-version = "1.85.0"
homepage = "https://bitcoindevkit.org"
repository = "https://github.com/bitcoindevkit/bdk"
documentation = "https://docs.rs/bdk_chain"
description = "Collection of core structures for Bitcoin Dev Kit."
license = "MIT OR Apache-2.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
# The compat layer branch: https://github.com/satsfy/rust-bitcoin/pull/38
bitcoin = { git = "https://github.com/satsfy/rust-bitcoin", branch = "units-compat-demo2", default-features = false, features = [
    "compat",
] }
bitcoin-units = { version = "0.1.101", git = "https://github.com/satsfy/rust-bitcoin", branch = "units-compat-demo2", default-features = false, features = [
    "alloc",
] }
bdk_core = { path = "../core", version = "0.6.2", default-features = false }
serde = { version = "1", optional = true, features = ["derive", "rc"] }
miniscript = { version = "13.0.0", git = "https://github.com/satsfy/rust-miniscript", branch = "units-compat-demo-13", optional = true, default-features = false }

# Feature dependencies
rusqlite = { version = "0.31.0", features = ["bundled"], optional = true }

[dev-dependencies]
rand = "0.8"
proptest = "1.2.0"
bdk_testenv = { path = "../testenv" }
criterion = { version = "0.7" }

[features]
default = ["std", "miniscript"]
std = ["bitcoin/std", "miniscript?/std", "bdk_core/std"]
serde = ["dep:serde", "bitcoin/serde", "miniscript?/serde", "bdk_core/serde"]
hashbrown = ["bdk_core/hashbrown"]
rusqlite = ["std", "dep:rusqlite", "serde"]

[[bench]]
name = "canonicalization"
harness = false

[[bench]]
name = "indexer"
harness = false
