use bitcoin::compat::Amount;

/// Balance, differentiated into various categories.
#[derive(Debug, PartialEq, Eq, Clone, Default)]
#[cfg_attr(feature = "serde", derive(serde::Deserialize, serde::Serialize))]
pub struct Balance {
    /// All coinbase outputs not yet matured
    #[cfg_attr(
        feature = "serde",
        serde(with = "bitcoin::compat::amount::serde::as_sat")
    )]
    pub immature: Amount,
    /// Unconfirmed UTXOs generated by a wallet tx
    #[cfg_attr(
        feature = "serde",
        serde(with = "bitcoin::compat::amount::serde::as_sat")
    )]
    pub trusted_pending: Amount,
    /// Unconfirmed UTXOs received from an external wallet
    #[cfg_attr(
        feature = "serde",
        serde(with = "bitcoin::compat::amount::serde::as_sat")
    )]
    pub untrusted_pending: Amount,
    /// Confirmed and immediately spendable balance
    #[cfg_attr(
        feature = "serde",
        serde(with = "bitcoin::compat::amount::serde::as_sat")
    )]
    pub confirmed: Amount,
}

impl Balance {
    /// Get sum of trusted_pending and confirmed coins.
    ///
    /// This is the balance you can spend right now that shouldn't get cancelled via another party
    /// double spending it.
    pub fn trusted_spendable(&self) -> Amount {
        (self.confirmed + self.trusted_pending).expect("sum of balances cannot exceed supply")
    }

    /// Get the whole balance visible to the wallet.
    pub fn total(&self) -> Amount {
        (self.confirmed + (self.trusted_pending + (self.untrusted_pending + self.immature)))
            .expect("sum of balances cannot exceed supply")
    }
}

impl core::fmt::Display for Balance {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(
            f,
            "{{ immature: {}, trusted_pending: {}, untrusted_pending: {}, confirmed: {} }}",
            self.immature, self.trusted_pending, self.untrusted_pending, self.confirmed
        )
    }
}

impl core::ops::Add for Balance {
    type Output = Self;

    fn add(self, other: Self) -> Self {
        Self {
            immature: (self.immature + other.immature)
                .expect("sum of balances cannot exceed supply"),
            trusted_pending: (self.trusted_pending + other.trusted_pending)
                .expect("sum of balances cannot exceed supply"),
            untrusted_pending: (self.untrusted_pending + other.untrusted_pending)
                .expect("sum of balances cannot exceed supply"),
            confirmed: (self.confirmed + other.confirmed)
                .expect("sum of balances cannot exceed supply"),
        }
    }
}
